<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="lista_arquetipos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="arquetipo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:int"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="linaje" type="xs:string"/>
              <xs:element name="fuerza" type="xs:int"/>
              <xs:element name="magia" type="xs:int"/>
              <xs:element name="agilidad" type="xs:int"/>
              <xs:element name="elemento_debilidad" type="xs:string"/>
              <xs:element name="imagen" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>